name = "cluster_env"
uuid = "30ada69b-35f3-45cf-af03-1133005bd72c"
authors = ["Jan Kocka <kockahonza@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
Geppetto = "7616020f-7d25-45ac-879d-3d4711576aab"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
NOMAD = "02130f1c-4665-5b79-af82-ff1385104aa0"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SSMCMain = "a75ad852-21c5-4a12-a12f-b1392bb0ea4b"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
NOMAD = "2.4.2"
